Verify the sobol sequence as used in the CosmoGrid

In [1]:
import os, h5py
import numpy as np
from sobol_seq import i4_sobol
from scipy.stats.qmc import Sobol
from icecream import ic

from msfm.utils import cosmogrid
from msfm.utils.input_output import read_yaml

In [2]:
cosmo_params_info = cosmogrid.get_cosmo_params_info("../../data/CosmoGridV1_original_metainfo.h5", "grid")

### verify with respect to the CosmoGrid
Differences in `Ob` are expected due to bugs in concept

In [30]:
# order like the Sobol sequence
labels = ["Om", "s8", "H0", "Ob", "ns", "w0"]
cosmo_grid_priors = np.array(
    [
        [0.1, 0.5],
        [0.4, 1.4],
        [64.0, 82.0],
        [0.03, 0.06],
        [0.87, 1.07],
        [-2.0, -0.333],
    ], dtype=np.float32
)

# TODO There's a bug with respect to h!

In [33]:
for i in range(len(cosmo_params_info)):
    cosmo_params = [cosmo_params_info[label][i] for label in labels]
    cosmo_params = np.array(cosmo_params, dtype=np.float32)

    i_sobol = cosmo_params_info["sobol_index"][i]
    sobol_point, _ = i4_sobol(6, i_sobol)
    sobol_params = sobol_point*np.squeeze(np.diff(cosmo_grid_priors)) + cosmo_grid_priors[:,0]
    sobol_params = sobol_params.astype(np.float32)

    if i_sobol == 60611:
        print(cosmo_params[2])
        print(sobol_params[2], "\n")

# in /home/ipa/refreg/data/data_products/CosmoGrid/raw/grid/cosmo_060611/run_0/params.yml:
# 68.8507385254

68.85074
73.063446 



In [27]:
counter = 0
for i in range(len(cosmo_params_info)):
    cosmo_params = [cosmo_params_info[label][i] for label in labels]
    cosmo_params = np.array(cosmo_params, dtype=np.float32)

    i_sobol = cosmo_params_info["sobol_index"][i]
    sobol_point, _ = i4_sobol(6, i_sobol)
    sobol_params = sobol_point*np.squeeze(np.diff(cosmo_grid_priors)) + cosmo_grid_priors[:,0]
    sobol_params = sobol_params.astype(np.float32)

    print(i_sobol)
    # print(np.isclose(sobol_params, cosmo_params, rtol=1e-3, atol=1e-5), "\n")
    print(cosmo_params[2])
    print(sobol_params[2], "\n")

    if not np.isclose(cosmo_params[2], sobol_params[2], rtol=1e-3, atol=1e-5):
        counter += 1

print(counter)

1
73.0
73.0 

2
68.5
77.5 

3
77.5
68.5 

4
66.25
75.25 

6
70.75
70.75 

10
80.875
74.125 

11
71.875
65.125 

12
74.125
80.875 

14
78.625
67.375 

19
75.8125
74.6875 

20
69.0625
72.4375 

22
64.5625
76.9375 

23
73.5625
67.9375 

28
81.4375
66.8125 

30
76.9375
80.3125 

34
78.90625
70.46875 

39
72.15625
72.71875 

44
64.28125
71.59375 

47
77.78125
67.09375 

54
74.96875
66.53125 

55
65.96875
75.53125 

56
69.34375
65.40625 

58
64.84375
78.90625 

62
67.09375
72.15625 

63
76.09375
81.15625 

66
73.984375
76.515625 

70
76.234375
65.265625 

71
67.234375
74.265625 

78
66.109375
68.640625 

79
75.109375
77.640625 

82
80.171875
71.453125 

84
73.421875
64.703125 

87
68.921875
69.203125 

90
70.046875
68.078125 

91
79.046875
77.078125 

95
81.296875
65.828125 

97
79.328125
71.734375 

98
65.828125
67.234375 

99
74.828125
76.234375 

100
72.578125
69.484375 

102
68.078125
73.984375 

106
75.953125
72.859375 

107
66.953125
81.859375 

110
73.703125
79.609375 

114
72.015625


### single example

In [3]:
# from https://cosmo-gitlab.phys.ethz.ch/jafluri/cosmogrid_kids1000/-/blob/master/kids1000_analysis/constants.py#L13
priors = np.array([[ 0.1  ,  0.5  ],
                   [ 0.4  ,  1.4  ],
                   [ 0.64 ,  0.82 ],
                   [ 0.03 ,  0.06 ],
                   [ 0.87 ,  1.07 ],
                   [-2.   , -0.333],
          np.log10([1.0e12, 1.0e15]),
                   [-2.   ,  2.   ],
                   [-3.   ,  3.   ]])

# /home/ipa/refreg/data/data_products/CosmoGrid/raw/grid/cosmo_011062/run_0
sobol_seed = 11062

# https://cosmo-gitlab.phys.ethz.ch/jafluri/cosmogrid_kids1000/-/blob/master/kids1000_analysis/input_pipeline.py#L461
sobol_point, _ = i4_sobol(9, sobol_seed)
Om, s8, h, Ob, ns, w0, log10_Mc, nu, a_ia = (sobol_point*np.squeeze(np.diff(priors)) + priors[:,0])

ic(Om)
ic(s8)
ic(h)
ic(Ob)
ic(ns)
ic(w0)
ic(log10_Mc)
ic(nu)
ic(a_ia)

# content of params.yml
# As: 8.122750437129466e-10
# bary_Mc: 2943968138429.53
# bary_nu: 1.037841796875
# H0: 68.5758056641
# O_cdm: 0.336458858089
# O_nu: 0.0013725628089999858
# Ob: 0.045737915039
# Ol: -1.0
# Om: 0.383569335937
# m_nu: 0.02
# ns: 0.990397949219
# pkd_seed: 222536
# s8: 0.618078613281
# sobol_seed: 11062
# w0: -1.073199279785
# wa: 0.0

ic| Om: 0.3835693359375
ic| s8: 0.61807861328125
ic| h: 0.734427490234375
ic| Ob: 0.0376263427734375
ic| ns: 0.99039794921875
ic| w0: -1.0731992797851562
ic| log10_Mc: 12.46893310546875
ic| nu: 1.037841796875
ic| a_ia: 2.3565673828125


2.3565673828125

### comparison to scipy (not necessary)

In [6]:
print(Sobol(d=5, scramble=False).fast_forward(10).random())
sobol_point, _ = i4_sobol(5, 10)
print(sobol_point)

[[0.9375 0.0625 0.6875 0.1875 0.3125]]
[0.9375 0.0625 0.5625 0.9375 0.3125]


In [7]:
sobol_point, _ = i4_sobol(5, 10)
print(sobol_point)
sobol_point, _ = i4_sobol(10, 10)
print(sobol_point)


[0.9375 0.0625 0.5625 0.9375 0.3125]
[0.9375 0.0625 0.5625 0.9375 0.3125 0.4375 0.8125 0.6875 0.4375 0.8125]


# config

In [ ]:
with h5py.File("../../data/CosmoGridV1_original_metainfo.h5") as f:
    meta_info = f["parameters/grid"][:]

In [3]:
conf_dir = "../../configs/config.yaml"
conf = read_yaml(conf_dir)

In [4]:
prior = np.array(conf["analysis"]["grid"]["prior"]["cosmo"])

In [5]:
prior

array([[ 0.64 ,  0.82 ],
       [ 0.03 ,  0.06 ],
       [ 0.1  ,  0.5  ],
       [ 0.87 ,  1.07 ],
       [ 0.4  ,  1.4  ],
       [-2.   , -0.333]])