In [15]:
import numpy as np
import healpy as hp

In [16]:
n_side = 512
A_pix = hp.nside2pixarea(n_side, degrees=True)

# Metacal

In [17]:
# from Table 1 in https://arxiv.org/pdf/2105.13543.pdf, in units of galaxies/deg^2
n_gal = np.array([1.476, 1.479, 1.484, 1.461])*60**2
print(n_gal)

# units of galaxies/pixel
n_gal *= A_pix
print(n_gal)

[5313.6 5324.4 5342.4 5259.6]
[69.68235489 69.8239857  70.06003703 68.97420088]


# Maglim

In [18]:
# from Table 1 in https://arxiv.org/pdf/2105.13540.pdf, in units of galaxies/deg^2
n_gal = np.array([0.15, 0.107, 0.109, 0.146, 0.106, 0.1])*60**2
print(n_gal)

# units of galaxies/pixel
n_gal *= A_pix
print(n_gal)

[540.  385.2 392.4 525.6 381.6 360. ]
[7.08154013 5.05149863 5.14591916 6.89269906 5.00428836 4.72102675]
