In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

tf.config.experimental.set_memory_growth(tf.config.list_physical_devices(device_type="GPU")[0], True)

In [2]:
class GaussianNoiseLayer(tf.keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super(GaussianNoiseLayer, self).__init__(**kwargs)
        self.stddev = tf.convert_to_tensor(stddev, dtype=tf.float32)

    def build(self, input_shape):
        if len(self.stddev.shape) == 0:
            self.stddev = tf.ones((input_shape[-1],)) * self.stddev
        elif self.stddev.shape[0] != input_shape[-1]:
            raise ValueError("Length of stddev does not match the number of input channels")

    def call(self, inputs):
        noise = tf.random.normal(shape=tf.shape(inputs), mean=0.0, stddev=self.stddev)

        return inputs + noise

In [3]:
sigmas = [1.0, 10.0, 100.0]
n_samples = 10

In [4]:
gaussian_noise_layer = GaussianNoiseLayer(stddev=sigmas)
gaussian_noise_layer.build(input_shape=(None, 3))

In [5]:
gaussian_noise_layer(tf.zeros((n_samples, 3)))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[-2.2556620e+00, -9.8276396e+00, -4.8133812e+01],
       [-8.8055688e-01,  3.2308016e+00,  2.1879690e+01],
       [-4.0427484e-02,  7.2169342e+00, -1.2013911e+02],
       [ 5.4974443e-01, -1.9184263e+01, -7.7051848e-01],
       [ 1.7879374e+00, -7.7007351e+00, -1.1375894e+02],
       [-2.1721320e-01,  5.7396674e+00,  1.8314302e+01],
       [ 6.4767319e-01,  5.7168221e+00,  1.5554942e+02],
       [-5.7883799e-01,  6.4226952e+00, -1.6169713e+02],
       [-9.1516113e-01, -1.0143429e+01,  2.6828197e+01],
       [ 9.1560310e-01, -2.1131876e+01,  3.6642725e+00]], dtype=float32)>

In [6]:
gaussian_noise_layer(tf.zeros((n_samples, 3)))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[ -0.55693746,   6.0469685 , -49.972202  ],
       [  0.38892975,  10.393495  ,  75.48643   ],
       [  0.56324434,  -8.510591  , -78.23776   ],
       [ -0.6767696 ,  -4.0210457 , -72.67236   ],
       [  0.4108433 ,   7.008443  ,  80.47106   ],
       [ -1.2157663 ,  -1.2995331 , -81.97433   ],
       [ -0.39914483,   1.4554608 ,  58.25526   ],
       [ -1.3551173 ,  -1.190019  , -45.00313   ],
       [ -0.8194545 ,  -5.61868   , -52.644558  ],
       [ -1.3966578 ,  -3.3084683 ,  88.718956  ]], dtype=float32)>

In [7]:
gaussian_noise_layer(tf.zeros((n_samples, 3)))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[-1.61826491e+00,  2.70472825e-01, -1.23668495e+02],
       [-1.87422499e-01,  6.10294580e+00,  2.72884521e+01],
       [ 1.81257391e+00, -2.60687494e+00,  1.87325653e+02],
       [-6.24832749e-01,  2.92306690e+01, -5.28910522e+01],
       [-1.44123882e-01, -1.08073053e+01, -2.09157059e+02],
       [-5.76689720e-01,  8.54086971e+00,  8.90992966e+01],
       [-4.83569384e-01,  1.17960119e+00, -4.60444659e-01],
       [-4.44578379e-01,  8.12320423e+00, -2.17982559e+01],
       [ 2.50049680e-01,  2.40092993e+00,  1.58039978e+02],
       [ 5.40692449e-01, -4.26285458e+00, -1.30041977e+02]], dtype=float32)>